In [17]:
import pandas as pd

In [18]:
s = pd.Series([1, 2, 3, 4, 5, 6, 7])
print(s.head())

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [19]:
data = pd.DataFrame({'Name': ["Hamza", "Ali", "Zoya", "Kareem", "Shahveez"],
                     'Age': [19, 28, 35, 26, 20],
                     'City': ["Mumbai", "Karachi", "New York", "Amritsar", "Singapore"],
                     'Category': ['A', 'B', 'A', 'B', 'C'],
                     'Salary': [2000, 1500, 2000, 1500, 1000]
                     })

data.head()
# data.info()
# data.describe()

       Name  Age       City Category  Salary
0     Hamza   19     Mumbai        A    2000
1       Ali   28    Karachi        B    1500
2      Zoya   35   New York        A    2000
3    Kareem   26   Amritsar        B    1500
4  Shahveez   20  Singapore        C    1000

In [24]:
print(data.index)

data.set_index('Age')

RangeIndex(start=0, stop=5, step=1)

         Name       City Category  Salary
Age
19      Hamza     Mumbai        A    2000
28        Ali    Karachi        B    1500
35       Zoya   New York        A    2000
26     Kareem   Amritsar        B    1500
20   Shahveez  Singapore        C    1000

In [39]:
first_row = data.iloc[0]

# print(first_row)
print(data.loc[::-1, ['Name', 'Age']])

       Name  Age
4  Shahveez   20
3    Kareem   26
2      Zoya   35
1       Ali   28
0     Hamza   19

In [44]:
print(data[data['Age']>20])

     Name  Age      City Category  Salary
1     Ali   28   Karachi        B    1500
2    Zoya   35  New York        A    2000
3  Kareem   26  Amritsar        B    1500

In [45]:
print(data.at[2, 'Category'])

A

In [65]:
data.query('Age==19 and Name=="Hamza"')

    Name  Age    City Category  Salary
0  Hamza   19  Mumbai        A    2000

In [74]:
series = pd.Series([1000, 500, 1000, 500, 200], name="Bonus")
series

0    1000
1     500
2    1000
3     500
4     200
Name: Bonus, dtype: int64

In [78]:
res = pd.concat([data, series], axis=1)
res

       Name  Age       City Category  Salary  Bonus
0     Hamza   19     Mumbai        A    2000   1000
1       Ali   28    Karachi        B    1500    500
2      Zoya   35   New York        A    2000   1000
3    Kareem   26   Amritsar        B    1500    500
4  Shahveez   20  Singapore        C    1000    200